### ISSUE TITLE
Crab decider immunity

### ISSUE THREAD

**Issue by sky-larke** [a11ce/katbot#5]
Crab decider module clearly seems to include the inability to target its creator. Rigged?????? Are you censoring katbot? 
<img width="330" alt="Screen Shot 2022-05-10 at 11 36 49 PM" src="https://user-images.githubusercontent.com/67734042/167770117-e6c423b2-17c9-4827-b6d0-82be8911c5bc.png">

**Comment by a11ce** [comment]
The crab decider immunity is just because of Discord's permission setup (this is what happens when Katbot can't change someone's name), but I will give her a better general-case error message.
